### PR TITLE
chore(rln-relay): update docs and .env.example to include http instead of ws rpc url

### PR DESCRIPTION
**Pull request by rymnc**
Updates the documentation, companion PR: https://github.com/waku-org/nwaku/pull/2442

### CODE REVIEW

**Comment by rymnc** [comment]
can't add reviewers, so pinging @alrevuelta @Ivansete-status @gabrielmer  here :)

**Review by gabrielmer — APPROVED** [review]
LGTM, thanks!

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks! :100:

**Comment by Ivansete-status** [comment]
@rymnc - I'll merge as I assume you don't have permission.

**Pull request merged**
