### PR TITLE
bump nwaku version

### PR DESCRIPTION
**Pull request by chair28980**
Bumps nwaku version in docker-compose.yml to 0.23.0.

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks!

**Review by gabrielmer — APPROVED** [review]
Thanks so much!

**Review by NagyZoltanPeter — APPROVED** [review]
All good! Thx.

**Comment by Ivansete-status** [comment]
:warning:  This change is needed indeed. Notice though that the users would need to completely remove their _Postgres_ databases because we introduced a new database attribute in the code. Still, we didn't create a proper migration script.

**Comment by Ivansete-status** [comment]
> Maybe I missed something. Why changing to `harbor.status.im`?

I don't know the reasons behind that movement. Do you know @apentori ?

**Comment by apentori** [comment]
> Maybe I missed something. Why changing to `harbor.status.im`?

Harbor is our internal docker registry, all image pushed there. We replicate the released version in docker hub.
Both registry are valid.

The version 0.23.0 is available :
* [docker hub](https://hub.docker.com/layers/wakuorg/nwaku/v0.23.0/images/sha256-e6e5b02a729d20b2fba9396750ed7dfd7c5a2c143e05a30eb90d6f4597e0627d?context=explore)
* [Harbor](https://harbor.status.im/harbor/projects/9/repositories/nwaku/artifacts-tab/artifacts/v0.23.0?publicAndNotLogged=yes)

**Pull request merged**
