### PR TITLE
Add row count and database size panels

### PR DESCRIPTION
**Pull request by fryorcraken**
Adding some postgres related panels using Prometheus source.

image

I will add panels with PostgreSQL source in follow-up PR.

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for it!
Maybe in the future, we could add some kind of "debug" toggle button to switch on/off panels that have high-consuming queries

**Comment by fryorcraken** [comment]
The one by content topic does not work. will need to remove before merging

**Review by alrevuelta — APPROVED** [review]
lgtm. @fryorcraken let us know when:

> The one by content topic does not work. will need to remove before merging

**Comment by fryorcraken** [comment]
Major fail on my side I think, I added panel to my "local library" before adding them to the dashboard and it seems after a restart they disappeared from the library and the dashboard shows "not found".
Trying again now..

**Comment by fryorcraken** [comment]
exposing port 5432 on postgres container was removed with this PR https://github.com/waku-org/nwaku-compose/commit/20f91f42428e3e91ab903aee561f2c1e10ace770 by @vpavlin.

Which means the panel I added won't work as Grafana needs to access postgres to generate them.

1. Can I revert this specific line?
2. Is there a way to expose a container's port to other containers but not host network?

**Comment by fryorcraken** [comment]
>     2. Is there a way to expose a container's port to other containers but not host network?

Using `expose`

**Comment by alrevuelta** [comment]
> Can I revert this specific line?

As long as its exposed locally `127.0.0.1` I'm fine with it unless someone else has other concerns.

**Pull request merged**
