### PR TITLE
feat: provide migration instructions to var name changes

### PR DESCRIPTION
**Pull request by fryorcraken**

### CODE REVIEW

**Comment by fryorcraken** [comment]
Follow-up to #100

**Review by rymnc — APPROVED** [review]
Change LGTM

**Review by alrevuelta — APPROVED** [review]
lgtm, though i dont think this kind of migration is needed. this adds complexity that starts to pile up. today is this new env but tomorrow is gonna be another one. we are not stable so breaking changes are expected.

**Comment by fryorcraken** [comment]
> lgtm, though i dont think this kind of migration is needed. this adds complexity that starts to pile up. today is this new env but tomorrow is gonna be another one. we are not stable so breaking changes are expected.

I agree with you which is why I went with this strategy, we can remove this patch at any point in the future if any of the files feels bloated.

**Pull request merged**
